#IN here all the application's properties are kept here. It has two format: (yaml), this is default (properties).
spring.application.name=practice

#You can change port no here. But it should be 4 digits.
server.port=8082