#IN here all the application's properties (configuration) are kept here. It has two format: (yaml), this is default (properties).
spring.application.name=practice

#You can change port no here. But it should be 4 digits.
server.port=8082

spring.datasource.url=jdbc:h2:mem:tododb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=0987

spring.h2.console.enabled=true